In [2]:
!pip install numpy

In [3]:
import numpy as np

In [37]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [65]:
#2.呈上題，將以上數列取出偶數。
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
#3.呈1題，將數列取出3的倍數。
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])